spring:
  datasource:
    driver-class-name: 'oracle.jdbc.driver.OracleDriver'
    jdbc-url: 'jdbc:oracle:thin:@211.189.132.188:1521/solsdb'
    username: 'ATMSADM'
    password: 'ATMSADM'

  second-datasource:
    driver-class-name: 'oracle.jdbc.driver.OracleDriver'
    jdbc-url: 'jdbc:oracle:thin:@211.189.132.201:1521/TCSSOLUTION'
    username: 'ATMSADM'
    password: 'ATMSADM'

  task:
    scheduling:
      pool:
        size: 10
server:
  port: 8086
logging:
  config: classpath:logback/logback-spring.xml
